server:
  port : 8042

spring:
  application:
    name: MuseumBackend

  datasource:
    url: jdbc:postgresql://localhost:5300/maindb
    username: ivan
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: g3645g663g6jkg6jkg645kgki2562uig62ilg63lk6g
  expiration: 86400000